### ISSUE TITLE
New version of Newtonsoft.Json

### ISSUE THREAD

**Issue by nikembala** [GHPReporter/Ghpr.NUnit#19]
Hello,
There is new version of Newtonsoft.Json
When I put the new version .dll I got the following error:

System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.TypeI
nitializationException: The type initializer for 'Ghpr.NUnit.Extensions.GhprEventListener' threw an exception. ---> Syst
em.IO.FileNotFoundException: Could not load file or assembly 'Newtonsoft.Json, Version=9.0.0.0, Culture=neutral, PublicK
eyToken=30ad4fe6b2a6aeed' or one of its dependencies. The system cannot find the file specified.
   at Ghpr.Core.Helpers.ReporterHelper.GetSettingsFromFile(String fileName)
   ...

Please, if possible, update to the new version of Newtonsoft.Json

**Comment by elv1s42** [comment]
Hi!
Sure, I will prepare an update for Ghpr packages

**Comment by elv1s42** [comment]
@nikembala this is done now, the new version is 0.4.6 for both Ghpr.Core and Ghpr.NUnit

**Comment by nikembala** [comment]
Thank you!
