### ISSUE TITLE
Report displays no data about specific runs

### ISSUE THREAD

**Issue by t2thefirst** [GHPReporter/Ghpr.NUnit#26]
It appears that my test results are not being properly written to the reporting tool. When viewing the report, I see the number of runs, and dates for those runs, but upon drilling into the individual runs, the main statistics and test list show that no tests were run.

Attached is my TestResults.xml files and the report generated from this run. The report uses the example data provided. [TestResult.zip](https://github.com/GHPReporter/Ghpr.NUnit/files/1323061/TestResult.zip)

Do you have any suggestions as to what I may have missed during the initial installation? Any help would be appreciated.

**Comment by elv1s42** [comment]
Hi @t2thefirst !

Thank you for this issue.
Unfortunately I can't reproduce this issue.
Are you using the latest versions of both NUnit Console and Ghpr.NUnit?
Are you following this (https://github.com/GHPReporter/Ghpr.NUnit#usage) instructions about how to run Ghpr for NUnit tests?

**Comment by t2thefirst** [comment]
Thank you for taking a look at my question. 
I am using the latest version of Nunit Console (3.7.0) and Ghpr.NUnit (installed again today via NUget). I'm also following the instructions you linked. 

Does it matter which version of Newtonsoft.Json.dll I use? My Ghpr.Nunit/Newtonsoft.Json.10.0.3 doesn't include a folder specifically for net452. I grabbed the Newtonsoft.Json.dll for my addins folder from net45.

**Comment by elv1s42** [comment]
Hi @t2thefirst ,

Unfortunately I'm not able to reproduce this issue.

Were you able to see test report generated from [Ghpr.NUnit.Examples](https://github.com/GHPReporter/Ghpr.NUnit.Examples) ?

**Comment by t2thefirst** [comment]
Hi @elv1s42, 
I'm not able to see results even with the test data from the Nunit.Examples.

Here is what I'm doing. 
Download [Ghpr.NUnit.Examples](https://github.com/GHPReporter/Ghpr.NUnit.Examples) as a zip.
Extract and build Ghpr.NunitExamples.sln with Xamarin Studio.
Using run the tests with a command to  command similar to nunit3-console.exe C:/Path/to/Ghpr.NUnitExamples.dll 
 I then get the result attached in my first comment.

**Comment by elv1s42** [comment]
Hi @t2thefirst !
I've updated NUnit.Examples repository with the latest Ghpr.Core and Ghpr.NUnit packages, can you please try generating the report once again?
Also please make sure that you have the latest NUnit.Console installed on your machine, see https://github.com/GHPReporter/Ghpr.NUnit#usage

**Comment by t2thefirst** [comment]
Thanks for taking a look. You were right in the first place that I was on an older version. 
My install of Ghpr.Nunit was using Ghpr.Core 0.6.0. It needs to be 0.7.0. Updating to the correct version resolved my issues. Issue #29 is the same behavior I was seeing.

**Comment by elv1s42** [comment]
@t2thefirst, thank you for the update!
