### ISSUE TITLE
Support report generation from .xml file

### ISSUE THREAD

**Issue by elv1s42** [GHPReporter/Ghpr.NUnit#27]
We need to create a new console application to generate the report from NUnit .xml test result file

**Comment by testingplusme** [comment]
Hello @elv1s42 can you do something with this? For me, it will be very helpful. In my opinion, Ghpr reporter is the best so it will be good for me, however, now execution isn't satisfying :(

**Comment by elv1s42** [comment]
Hi @jakismichal ,

We are looking to release this feature in the mext release for v 0.9

Thank you

**Comment by testingplusme** [comment]
@elv1s42 Awesome :)
Also, Thank you. I saw that you created this project :) Do you know when it will be possible to download?

**Comment by elv1s42** [comment]
Hi @jakismichal !
This should work now with Ghpr.Console v0.8.0.2:
https://github.com/GHPReporter/Ghpr.Console

Thank you
