### ISSUE TITLE
NullReferenceException on SaveScreenshot()

### ISSUE THREAD

**Issue by nikembala** [GHPReporter/Ghpr.NUnit#28]
Hello,

Please review the exception we have, here is the stacktrace:

...
TearDown : System.TypeInitializationException : The type initializer for 'Ghpr.NUnit.Extensions.GhprEventListener' threw an exception.
----> System.NullReferenceException : Object reference not set to an instance of an object.
--TearDown
at Ghpr.NUnit.Extensions.GhprEventListener.get_OutputPath()
at Ghpr.NUnit.Utils.ScreenHelper.SaveScreenshot(Byte[] screenBytes)
...

Setup is Specflow + Selenium. Exception does not appear on all dev's computers. Running version 0.5.0.2 of both Core&NUnit.

If more information is needed please request so I can deliver.

Regards,

**Comment by elv1s42** [comment]
Hi @nikembala !

Can you please try to reproduce this issue with the latest Ghpr.NUnit version (v 0.7.0.0)?

**Comment by nikembala** [comment]
done
Issue was reproduced with 0.7.0
result is the same

**Comment by elv1s42** [comment]
Thank you!
I'll try to reproduce and fix this

**Comment by nikembala** [comment]
Hello,
Could this error appear if something is missing in any of the configuration files ?
Regards,

**Comment by elv1s42** [comment]
Hi @nikembala !

Can you please make sure, that you have .json config file in your solution and it appears in the build folder?
For example, you can set 'Copy Always' option for .json config file:
![image](https://user-images.githubusercontent.com/6689884/31320547-016e5044-ac7f-11e7-8f02-ef05c1fee6fb.png)

**Comment by nikembala** [comment]
Hi @elv1s42 , please excuse me for the late comment - the issue was resolved and the reason as you stated it - the settings files was not in the required directory. Thank you for the help!
