### ISSUE TITLE
No tests in the json files : All zeros

### ISSUE THREAD

**Issue by xenaree** [GHPReporter/Ghpr.NUnit#29]
Hello, 
I followed the steps from the github tutorial, but everytime i run my tests (2 selenium tests, nunit, c#) via the console runner, the generated json files are created with 0 results.

`{"testRunFiles":[],"runInfo":{"guid":"2a45c56d-7034-4004-b110-415ec14891a3","start":"2017-10-09T13:29:37.3339941+02:00","finish":"2017-10-09T13:30:26.2869285+02:00","fileName":"run_2a45c56d-7034-4004-b110-415ec14891a3.json"},"sprint":"","name":"","summary":{"total":0,"success":0,"errors":0,"failures":0,"inconclusive":0,"ignored":0,"unknown":0}}`

Regards,
Kais

**Comment by PYasonau** [comment]
@xenaree Hi. This is because you use GHRP.Core.dll version 0.6.0. Please, change it to 0.7.0 in nuget manager, rebuild your project and replace with new dll. After that you will have tests in your tests results

**Comment by xenaree** [comment]
That was it. Thank you!
