### ISSUE TITLE
Update nunit.framework reference in Ghpr.NUnit to NUnit version 3.9.0

### ISSUE THREAD

**Issue by GitSIPA** [GHPReporter/Ghpr.NUnit#30]
Hi!

We updated our NUnit version today from 3.7.1 to version 3.9.0 which was released two days ago.
https://github.com/nunit/nunit/releases/tag/3.9

Unfortunately we have now troubles getting Screenshots for our GHPReports.

This is the error message we get: 
`System.IO.FileLoadException: Could not load file or assembly 'nunit.framework, Version=3.7.1.0, Culture=neutral, PublicKeyToken=2638cd05610744eb' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)
File name: 'nunit.framework, Version=3.7.1.0, Culture=neutral, PublicKeyToken=2638cd05610744eb'
   at Ghpr.NUnit.Utils.ScreenHelper.SaveScreenshot(Byte[] screenBytes)`

We figured out, that there is still a reference to NUnit 3.7.1. 

![ghpr_nunit](https://user-images.githubusercontent.com/1035887/32728786-f26b497a-c881-11e7-87fb-f0eabf08a430.png)

Would you mind updating it to the latest version and plan a release for GHPReporter?

**Comment by elv1s42** [comment]
Hi @GitSIPA, this is released now.
Thank you
