### ISSUE TITLE
Support .NET 4.6.2

### ISSUE THREAD

**Issue by ramiputchakayala** [GHPReporter/Ghpr.NUnit#31]
Hi ,

We are using the framework 4.6.2 and looking for instructions on how we can use the tool through command line 

version:NUnit.ConsoleRunner.3.7.0

Regards
RP

**Comment by elv1s42** [comment]
Hi @ramiputchakayala !

Thank you for this issue.
At the moment only net40 and net452 are supported, but more versions will be added in the future.

**Comment by ClassyCircuit** [comment]
It's been 2 years, are you ever going to support 4.6 ?

**Comment by elv1s42** [comment]
Hi @janissimsons .
Yes, the work is in progress to support multiple frameworks in Ghpr.Core: 
https://github.com/GHPReporter/Ghpr.Core/pull/113

After this is done NUnit repository will be updated.

**Comment by elv1s42** [comment]
Done.
