### ISSUE TITLE
Can we rename the "runs" in plotly chart/pic presentation with build number or 

### ISSUE THREAD

**Issue by nitinchawda** [GHPReporter/Ghpr.NUnit#32]
Highlighted
![image](https://user-images.githubusercontent.com/18319409/32885003-212e6072-caf7-11e7-9cb5-903697c6e3c2.png)

**Comment by elv1s42** [comment]
Hi @nitinchawda !

By default all test runs are called `run n`, where n is current number of runs.
You can specify run name by inserting it in .json config file.

**Comment by nitinchawda** [comment]
Thanks, i have modified it and it did work :)

**Comment by elv1s42** [comment]
Cool, thanks for confirming!
