### ISSUE TITLE
Is there any way to aggregate the different runs(libraries - similar to multiple test suites) and display the report similar to individual test library run report

### ISSUE THREAD

**Issue by nitinchawda** [GHPReporter/Ghpr.NUnit#33]

**Comment by elv1s42** [comment]
Hi @nitinchawda !

If you are using NUnit then it is possible to combine several test libraries into one `.nunit` project.
For more information please see: https://github.com/nunit/docs/wiki/NUnit-Test-Projects

Also you can take a look at example of such project files in our NUnit examples repository:
https://github.com/GHPReporter/Ghpr.NUnit.Examples/blob/master/Ghpr.NUnitExamples/SomeTests.nunit
When you are running tests from `.nunit` project via NUnit Console with Ghpr.NUnit addin then all tests from all test libraries will be combined into one report.

Also Ghpr.Console will support multiple result files as arguments soon. So it will be possible to generate one report from serveral result files.

Thank you

**Comment by nitinchawda** [comment]
Hi Evgeniy, Thanks for responding. I got what you meant. But i think i missed out important part in my query to post. Sorry for that :)

My query:
1) Each test suites in Different build configuration under Teamcity - (Why different - each test library runs have different tests meant with different setup required)  
2) Each have test report tabs displaying individual test report - (running single test library)
3) Get all the test reports from each configurations - test reports, combine them to get the overall test runs from (different build configurations or builds) to generate an aggregate report. 

I hope this clears what i meant :)

**Comment by elv1s42** [comment]
Ok, I see what you mean.
Am I right that you have several reports created in different folders?

The most simple workaround here is to use nunit test result `.xml` files, then pass them to Ghpr.Console to generate aggregate report. Can you please let me know if this workaround will work for you? If so, then I can add support for multiple files in Ghpr.Console

**Comment by nitinchawda** [comment]
Hi Evgeniy,

I couldn't try it out immediately but i did try it out today and the package Ghpr.Console nuget failed to install with following errors:

Install-Package : Error downloading 'Ghpr.Core.0.8.0.2 : Newtonsoft.Json [10.0.3, )' from 
'https://api.nuget.org/v3-flatcontainer/ghpr.core/0.8.0.2/ghpr.core.0.8.0.2.nupkg'.
At line:1 char:1
+ Install-Package Ghpr.Console -Version 0.8.0.2
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Install-Package], Exception
    + FullyQualifiedErrorId : NuGetCmdletUnhandledException,NuGet.PackageManagement.PowerShellCmdlets.InstallPackageCommand

**Comment by elv1s42** [comment]
Hi @nitinchawda !

I've tested installation via NuGet and it worked for me:
![image](https://user-images.githubusercontent.com/6689884/35511689-f6edd6de-050d-11e8-840a-13a0cc5d6315.png)

**Comment by nitinchawda** [comment]
Hi Evgeniy,

Can we install this package outside visual studio? I do not want it to install just under specific project or visual studio alone. I see that outside of VS it doesn't download the dependencies correctly for me. 

Something not working when installing outside VS.

Thanks

**Comment by nitinchawda** [comment]
Hi Evgeniy,

Can we install this package outside visual studio? I do not want it to
install just under specific project or visual studio alone. I see that
outside of VS it doesn't download the dependencies correctly for me.

Something not working when installing outside VS.

Thanks

**Comment by elv1s42** [comment]
Hi @nitinchawda !

Can you please let me know how do you download and install that package without visaul studio?
Simple copy/paste should work for you.

Thank you

**Comment by nitinchawda** [comment]
Hi Evgeniy,

I have been able to download the packages successfully. But the multiple
.xml (different test run dll) results when passed on to the
Ghpr.Console.exe it is not giving me the different packages in the
index.html.

I passed the argument as:  Ghpr.Console.exe "testresult1.xml" "testresult2.xml"

This way it takes only first xml and generates the report. it doesn't take second test result (testresult2.xml), 
Is it correct way to pass multiple path as above?
Can you please suggest what could be the issue? If possible can you connect
with me on skype: nchawda1

Thanks,
Nitin Chawda

**Comment by elv1s42** [comment]
Hi @nitinchawda !

At the moment multiple files processing is not supported yet, this feature will be added int the next release. So in the future you will be able to generate one test run from several result files.

Now you can run Ghpr.Console several times and pass a new file name each time. It will generate one report with several test runs.

Thank you.

**Comment by elv1s42** [comment]
Hi @nitinchawda!
You can try using Ghpr.Console to generate one report from several .xml results file.
Closing this issue
