### ISSUE TITLE
Unable to generate the Ghpr report

### ISSUE THREAD

**Issue by sathishkumarmani-cesltd** [GHPReporter/Ghpr.NUnit#34]
Hi,

I have tried to implement Ghpr report and followed all the steps as mentioned in readme file....however I am not able to generate a report. Below are the steps which I have followed
-> I couldn't find any folder with name addins, so i have created a new folder under ".nuget\packages\nunit.consolerunner\3.8.0\addins" and added all required dlls into it.
-> There is no "nunit.engine.addins" file available, so manually created a file under ".nuget\packages\nunit.consolerunner\3.8.0\tools" and added the path as "../../addins/Ghpr.NUnit.dll"

Please find the dll's versions I have used:
Nunit : 3.9.0
Newtonsoft.Json : 10.0.3
NUnit Console : 3.8.0
Ghpr.NUnit : 0.8.0.2

Could you please help me on resolving this issue

Regards,
Sathish Kumar Mani

**Comment by elv1s42** [comment]
Hi @sathishkumarmani-cesltd !

For using Ghpr.NUnit you need to install NUnit Console:
https://github.com/nunit/nunit-console/releases

After that you will be able to see the addins folder:
![image](https://user-images.githubusercontent.com/6689884/35576810-f914f206-05f0-11e8-91f7-030d12f1c4bc.png)


Thank you

**Comment by sathishkumarmani-cesltd** [comment]
@elv1s42 Thanks for the quick response :-). As I mentioned earlier I have installed NUnit console version 3.8.0
![image](https://user-images.githubusercontent.com/26871121/35577579-e977bbe6-0607-11e8-8d81-b9f141110f2d.png)

![image](https://user-images.githubusercontent.com/26871121/35577633-02fbe8b2-0608-11e8-976a-737a18043c8d.png)

No dlls or folders under NUnit console folder (Screenshot of nunit.console\3.8.0)

![image](https://user-images.githubusercontent.com/26871121/35578657-c5163284-060a-11e8-9027-07edfe75916f.png)

Screenshot of NUnit.ConsoleRunner/3.8.0/tools

![image](https://user-images.githubusercontent.com/26871121/35578791-18818658-060b-11e8-9e1e-029934451873.png)

**Comment by elv1s42** [comment]
Hi @sathishkumarmani-cesltd 

The NUnit Console should be installed on your local machine via running `.msi` file, not via NuGet:
![image](https://user-images.githubusercontent.com/6689884/35588520-f70c0cda-0611-11e8-8ee3-70d4612b38ca.png)

![image](https://user-images.githubusercontent.com/6689884/35588533-ffc95620-0611-11e8-9de8-337540bdab80.png)

Then you will be able to see the `addins` folder:
![image](https://user-images.githubusercontent.com/6689884/35588563-170b5270-0612-11e8-84ab-15e8c3f1e04b.png)

Also I'll take a look on how to use addins with NuGet packages.

Thank you

**Comment by sathishkumarmani-cesltd** [comment]
Thanks for the detailed response.. I have installed nunit console and have tried to run the test from nunit console. Now I am getting another error as shown below:

![image](https://user-images.githubusercontent.com/26871121/35619963-9d0678ee-06a5-11e8-98cf-177ed1b6153e.png)

However When I remove the addins/Ghpr.NUnit.dll from addins file, I am able to run the test..

Please help and let me know how to configure tests to view history of runs

**Comment by sathishkumarmani-cesltd** [comment]
Hi, I am able to generate the report after adding Nunit.engine dll in addins folder.. Thanks

**Comment by elv1s42** [comment]
Hi @sathishkumarmani-cesltd , thank you very much for the update.
I'll take a look at NuGet packages for Ghpr.NUnit as it looks like NUnit.Engine package should be updated

**Comment by georgooty** [comment]
Hi @sathishkumarmani-cesltd,

I'm also facing the same issue. I'm copied the Nunit.engine dll into addins folder. But the issue still exists.
can you please let me know , if anything you did additionally?

Regards,George

**Comment by sathishkumarmani-cesltd** [comment]
Hi George,
Could you please share the dlls and their versions and please share the screenshot as well to look into detail..

Thanks

**Comment by georgooty** [comment]
Ghpr.Core  - 0.8.0.2
Ghpr.NUnit - 0.8.0.2
NUnit - [3.9.0]
NUnit.ConsoleRunner - 3.8.0
![nunitconsole](https://user-images.githubusercontent.com/266172/35685388-964c6a28-078f-11e8-8a0a-55b6449c920b.PNG)

**Comment by elv1s42** [comment]
Hi @sathishkumarmani-cesltd , hi @georgooty !

The new version is released now. The issue was with Ghpr.NUnit which was using the previous version of NUnit.Engine (v 3.7.0 instead of v 3.8.0).

Thank you

**Comment by ManuelVelazquez** [comment]
Hello, @elv1s42  

I can not create the Ghpr report. Could anyone help me on this?

Please find the dll's versions I am using:

Nunit : 3.12
Newtonsoft.Json : 12.0.3.23909
NUnit Console : 3.11.1
Ghpr.NUnit : 0.9.10.0

This is how addins folder looks like:
![Capture](https://user-images.githubusercontent.com/25473907/77109055-e267bd00-69e8-11ea-9550-6cb6c40361d9.PNG)

This is how nunit.bundle.addins file looks like:
![image](https://user-images.githubusercontent.com/25473907/77109246-32df1a80-69e9-11ea-9d55-891a52dddbfb.png)

And this is how bin/debug folder looks like:
![image](https://user-images.githubusercontent.com/25473907/77110509-4b503480-69eb-11ea-9271-e8c569f7a2e4.png)



I am running via console like this:
nunit3-console.exe --labels=All --out=TestResult.txt "--result=TestResult.xml;format=nunit3" "C:\\users\usuario\project,project.dll"
![image](https://user-images.githubusercontent.com/25473907/77110381-20fe7700-69eb-11ea-9420-ee3cd636e371.png)

The testResult.txt and TestResul.xml files are generated successfully, but can NOT see the Ghpr Report... Am I missing some step?

**Comment by elv1s42** [comment]
Hi @ManuelVelazquez!

The first thing I'll suggest is to check the relative path inside your `nunit.bundle.addins` file.
You can use `--list-extensions` command to make sure `NUnit Console` sees the `Ghpr.NUnit` extension:
![image](https://user-images.githubusercontent.com/6689884/77187258-3bb51680-6ae5-11ea-9fa9-9f905fcb9b14.png)


Thank you
