### ISSUE TITLE
Newtonsoft.json v11 not supported

### ISSUE THREAD

**Issue by Sedemicra** [GHPReporter/Ghpr.NUnit#35]
Hello,
There is new version of Newtonsoft.Json: v11
Upgrading to it causes the following error:
`System.Reflection.TargetInvocationException : Exception has been thrown by the target of an invocation.
  ----> System.TypeInitializationException : The type initializer for 'Ghpr.NUnit.Extensions.GhprEventListener' threw an exception.
  ----> System.IO.FileNotFoundException : Could not load file or assembly 'Newtonsoft.Json, Version=10.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed' or one of its dependenci
es. The system cannot find the file specified.`

It would be much appreciated if you cold update and add the support for new version. 
Thanks in advance!

**Comment by elv1s42** [comment]
Hi @axinom-raido !

I'll prepare the new release with updated packages.
Will close the issue after new package will be uploaded

Thank you

**Comment by elv1s42** [comment]
Hi @axinom-raido , new Core and NUnit packages has been uploaded
