### ISSUE TITLE
Support Attachment Nodes for Screenshot Mapping

### ISSUE THREAD

**Issue by seanhotaling** [GHPReporter/Ghpr.NUnit#37]
With recent releases of NUnit, `AddTestAttachment(string filePath, string description = null);` allows screenshots to now be mapped to the test case: https://github.com/nunit/docs/wiki/TestContext.

```xml
<test-case>
  <output>...</output>
  <attachments>
    <attachment description="This is a description of this screenshot.">
      <filePath></filePath>
    </attachment>
    <attachment description="This is a description of this screenshot.">
      <filePath></filePath>
    </attachment>
  </attachments>
</test-case>
```

This would reduce the need for ScreenHelper.

**Comment by elv1s42** [comment]
Hi @sean-hotaling !

Thank you for this issue.
Agreed to support NUnit test attachments in the generated report. But ScreenHelper will be supported because there are some upcoming changes with general Ghpr.Core structure to support the ability of saving test results ont only as local .json files but as database records too.

Thanks.

**Comment by elv1s42** [comment]
All additional output will be stored under a separate tab like this:
![image](https://user-images.githubusercontent.com/6689884/41734791-ad9edb74-7590-11e8-9adc-5a261eb09044.png)

**Comment by seanhotaling** [comment]
@elv1s42, is this in reference to the above enhancement or #36?

**Comment by elv1s42** [comment]
@sean-hotaling yes, sorry. 
I had both issues opened in different tabs.

**Comment by elv1s42** [comment]
By default all attachments with extentions `.png`, `.jpeg` and `.bmp` will be considered as test screenshots and displayed in the report.

**Comment by elv1s42** [comment]
This now has been released too. Please see the release notes [here](https://github.com/GHPReporter/Ghpr.Core/blob/master/RELEASE_NOTES.md#v09)

**Comment by seanhotaling** [comment]
@elv1s42, thanks much!  ~~Will this be updated to be used from your console package?~~  It looks like the suite output will show in the report but not the screenshots from the attachment nodes.

Edit: Nothing to do with the console package, sorry.  I did notice though that you save the screenshots into a `TestScreenshotDto` within `GhprTestCase`, but nothing is ever done with those screenshots.  It seems like the only screenshots making it into the json are the ones from `GhprTestRun.Screenshots`.

**Comment by elv1s42** [comment]
Hi @sean-hotaling ,
This now should work for both NUnit Console Addin (this package) and Ghpr.Console package (used to generate reports from `.xml` results file).

Thank you.

**Comment by elv1s42** [comment]
Please use the latest version which is v.0.9.1

**Comment by seanhotaling** [comment]
@elv1s42, thanks for the quick updates.  Unfortunately, I installed 0.9.1 and am still not seeing those screenshots in the report.  I see the /img/ folder created now with my screenshot copied over, but the controller isn't picking it up: `screensInfo.length` in the controller is 0.

**Comment by elv1s42** [comment]
@sean-hotaling Sorry, I'll try to debug and fix it tomorrow then

**Comment by elv1s42** [comment]
Hi @sean-hotaling, it should finally work in v0.9.1.1
