### ISSUE TITLE
Ghpr.NUnit/Ghpr.Console does not work with NUnit.Engine3.9.0

### ISSUE THREAD

**Issue by rommel-baltazar** [GHPReporter/Ghpr.NUnit#38]
Hi,

There's is a new version of NUnit.Engine (3.9.0) and I have found out that report does not get generated with this version. Workaround is to roll back NUnit.Engine to 3.8.0.

**Environment:**
Ghpr.Console                      {0.9.2}                                                                                                                                       
Ghpr.Core                           {0.9.2}                  
Ghpr.LocalFileSystem          {0.9.2}                                                                                                   
Ghpr.MSTest                        {0.9.2.1}                                                                                                                                                  
Ghpr.NUnit                          {0.9.2}     
Newtonsoft.Json                  {11.0.2}                                                                                                                                                       
NUnit                                   {3.10.1}                                                                                                                                                        
NUnit.Console                     {3.9.0}                                                                                                                                                         
NUnit.ConsoleRunner          {3.9.0}                                                                                                                                                        
NUnit.Engine                       {3.8.0}      

**Steps To Reproduce:**
1. Run Test via nunit console runner
2. Run Ghpr console against the   generated xml test result file

**Result:**
Folder defined in  Ghpr.NUnit.Settings.json does not get created and report is not generated

**Comment by elv1s42** [comment]
Hi @rommel-baltazar !
Thank you for detailed issue, I've updated NUnit.Engine package in both Ghpr.NUnit and Ghpr.Console projects, please use the latest v0.9.2.1 of both packages.

Thank you
