### ISSUE TITLE
[Feature] Support .net core 2.0

### ISSUE THREAD

**Issue by elv1s42** [GHPReporter/Ghpr.NUnit#42]
add new target

**Comment by elv1s42** [comment]
related to https://github.com/GHPReporter/Ghpr.Core/issues/54

**Comment by mcopjan** [comment]
Hi @elv1s42, when are you planning to roll this out please? We would like to use this tool to create Nunit reports but out test project is build on .netCore 2.2 and we are using https://github.com/nunit/docs/wiki/NUnitLite-Runner to execute our tests (hence there is no .addins file etc.).

**Comment by elv1s42** [comment]
Hi @mcopjan !

Yes, this one is in progress.
At the moment I have `.Core` version of the Ghpr NuGet package (not published yet), but there may be some issues with the way Ghpr package will be discovered by NUnit Engine. You check another thread for more details here:
https://github.com/nunit/nunit-console/issues/487#issuecomment-511121027

For now I don't have much time to investigate this deeper, so most likely I'll publish the existing Ghpr code with `.Core` target framework and try to fix possible issues in the next release.

Thank you

**Comment by elv1s42** [comment]
Done
