### ISSUE TITLE
'nunit.engine.addins' file and location changed. Need to update Readme file

### ISSUE THREAD

**Issue by zhuyumi** [GHPReporter/Ghpr.NUnit#48]
**Describe the bug**
In the latest Nunit Console install package, the file 'nunit.engine.addins' has changed it's name and path.
Which means, https://github.com/GHPReporter/Ghpr.NUnit this readme doc is out dated. 
It confused me a while before I realized what wrong was it.

Old Name:  nunit.engine.addins
Old Path: \YOURLOCATION\NUnit.org\nunit-console\addins
New Name: nunit.**bundle**.addins
New Path: \YOURLOCATION\NUnit.org\nunit-console

**To Reproduce**
1. Go to https://github.com/nunit/nunit-console/releases 
2. Download and install `NUnit.Console-3.9.0.msi`
3. Go to installed folder C:\Program Files (x86)\NUnit.org\nunit-console
4. As you can see in the screenshot, there is no such file as 'nunit.engine.addins' in \addins folder anymore. Instead, a new file 'nunit.bundle.addins' has been added to the root nunit-console folder.

**Expected behavior**
In the Nunit readme file: https://github.com/GHPReporter/Ghpr.NUnit, we should change these places accordingly:
![image](https://user-images.githubusercontent.com/9000985/51796564-220a9d00-225b-11e9-9cdd-891f93b9b26f.png)

**Screenshots**
![image](https://user-images.githubusercontent.com/9000985/51796542-9133c180-225a-11e9-90e4-db948e0129fe.png)
![image](https://user-images.githubusercontent.com/9000985/51796545-9e50b080-225a-11e9-865a-431e003f7927.png)

**Desktop (please complete the following information):**
 - OS: [Windows 10, 64bit]

**Additional context**
I have tried, modify the new **nunit.bundle.addins** file will generate the result report.

**Comment by elv1s42** [comment]
Hi @woshizhuyumi !

Thank you very much for the detailed issue report, I've update the README file.

Best regards,
Evgeniy
