### ISSUE TITLE
NUnit Test Attachments aren't working as Screenshots

### ISSUE THREAD

**Issue by vanderkyl** [GHPReporter/Ghpr.NUnit#52]
**Describe the bug**
I am trying to add screenshots to the GHP report by using Nunit Test Attachments. The attachment is in the test result xml file, but it is not showing up in the html report.

Here is the screenshot code. This occurs in [TearDown]:

                var screenshot = ((ITakesScreenshot)Driver.Get()).GetScreenshot();
                string fileName = CurrentTestNameToJPG();
                screenshot.SaveAsFile(fileName);
                TestContext.AddTestAttachment(fileName, "Failure Screenshot");

And here is the attachment in the xml file:

`<attachments>
    <attachment>
      <filePath>C:\Screenshots\TQAA1271_SuccessfulStudentLogin_20190506_16-47-15.jpeg</filePath>
    <description>
      <![CDATA[Failure Screenshot]]>
    </description>
  </attachment>
</attachments>`

**Expected behavior**
The screenshot should show up in the GHP report under "Screenshots"
![Screenshotsghpr](https://user-images.githubusercontent.com/3710375/57260547-b8541900-7029-11e9-85f2-6d44c519d629.png)

**GHPR Version** - 0.8.0.2
**NUnit 3 Console** - 3.7

**Comment by elv1s42** [comment]
Hi @vanderkyl !

This functionality was release later.
Please see the release notes for more details: 
https://github.com/GHPReporter/Ghpr.Core/blob/master/RELEASE_NOTES.md#v09

The corresponding issue with feature request: 
https://github.com/GHPReporter/Ghpr.NUnit/issues/37
