### ISSUE TITLE
Could you help me solve this issue?

### ISSUE THREAD

**Issue by LiaoMin777** [GHPReporter/Ghpr.NUnit#54]
Ghpr.NUnit.Settings.json could not be read

**Comment by elv1s42** [comment]
Hi @LiaoMin777 !
Please check that you have the latest version of the packages as the structure changed a little bit: https://github.com/GHPReporter/Ghpr.Core#about-settings-file

Please see [Release notes](https://github.com/GHPReporter/Ghpr.Core/blob/master/RELEASE_NOTES.md#v099) for more details.

Thank you

**Comment by elv1s42** [comment]
Please feel free to come back with more questions or create a new issue/feature request.
Closing this one.
