### ISSUE TITLE
Screenshot added via NUnit TestContext.AddTestAttachment does not display GHPReport

### ISSUE THREAD

**Issue by msscribner** [GHPReporter/Ghpr.NUnit#67]
Screenshot is not displaying in the GHPReport

From a Selenium Test, I'm adding creating a screen shot and adding it to the NUNIT log:
    TestContext.AddTestAttachment("C:\\temp\\emailName.JPG");

Generated XML looks something like:
![image](https://user-images.githubusercontent.com/45525002/67502035-457c4000-f653-11e9-8da3-b4d0742e6de3.png)

To generate the GHPReport, I'm including NuGet packages:
![image](https://user-images.githubusercontent.com/45525002/67502130-6e043a00-f653-11e9-8d7d-d4a03d924d30.png)

I'm expecting to see the .jpg in the Screenshots link, but it does not display:

![image](https://user-images.githubusercontent.com/45525002/67492269-275b1380-f644-11e9-8313-9b06cb054d6a.png)

The **test_20191023_191447000.json** look like:
{
	"name": "ParallelTest_A_00",
	"fullName": "AutomationTests.ParallelTests.ParallelTest_A.ParallelTest_A_00",
	"description": null,
	"duration": 0.262805,
	"testStackTrace": "   at AutomationTests.Base.BaseTest.ExecuteTest(Action action, DriverType driverType, String strTestName) in C:\\TFS\\QAAutomation\\AutomationTests\\Base\\BaseTest.cs:line 71\r\n   at AutomationTests.ParallelTests.ParallelTest_A.ParallelTest_A_00() in C:\\TFS\\QAAutomation\\AutomationTests\\ParallelTest_A.cs:line 106",
	"testMessage": "System.Exception : Retries Exceeded.  Exception: NUnit.Framework.AssertionException:   Expected: True\r\n  But was:  False\r\n\r\n   at NUnit.Framework.Assert.ReportFailure(String message) in D:\\a\\1\\s\\src\\NUnitFramework\\framework\\Assert.cs:line 394\r\n   at NUnit.Framework.Assert.That[TActual](TActual actual, IResolveConstraint expression, String message, Object[] args) in D:\\a\\1\\s\\src\\NUnitFramework\\framework\\Assert.That.cs:line 241\r\n   at AutomationTests.ParallelTests.ParallelTest_A.<>c.<ParallelTest_A_00>b__2_0() in C:\\TFS\\QAAutomation\\AutomationTests\\ParallelTest_A.cs:line 104\r\n   at AutomationTests.Base.BaseTest.ExecuteTest(Action action, DriverType driverType, String strTestName) in C:\\TFS\\QAAutomation\\AutomationTests\\Base\\BaseTest.cs:line 46  1)   Expected: True\r\n  But was:  False\r\n\r\n",
	"result": "Failed: Error",
	"testType": null,
	"output": {
		"itemName": "test_output_20191023_191447000.json",
		"date": "2019-10-23T19:14:47Z"
	},
	"priority": null,
	"categories": [
		"P22"
	],
	"testInfo": {
		"guid": "493c9583-7c24-0582-5194-66ed161b96b3",
		"start": "2019-10-23T19:14:46Z",
		"finish": "2019-10-23T19:14:47Z",
		"itemName": "test_20191023_191447000.json"
	},
	"runGuid": "651dc1f6-0ead-4436-b808-1998debd6979",
	"screenshots": [],
	"events": [],
	"testData": [],
	"FailedOrBroken": true,
	"TestResult": 2
}

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Chrome

**Comment by elv1s42** [comment]
Hi @msscribner !
Thank you for the issue, I'll try to reproduce it. 
Are you running the tests in parallel? Are you doing it on the [framework level](https://github.com/nunit/docs/wiki/Framework-Parallel-Test-Execution) or on [engine level](https://github.com/nunit/docs/wiki/Engine-Parallel-Test-Execution)?

**Comment by msscribner** [comment]
I believe the answer to your question ( framework level
<https://github.com/nunit/docs/wiki/Framework-Parallel-Test-Execution>
vs engine
level <https://github.com/nunit/docs/wiki/Engine-Parallel-Test-Execution>)
is Framework.level.  But in this case, I'm only executing a single test.

Test are configured as:
        [TestFixture, Parallelizable(ParallelScope.All)]

. . .

        [Test, Category(Category.P22), Retry(1)]
        public void ParallelTest_A_00()
        {
            string strTestName = "ParallelTest_A_00";

            Action action = () =>
            {
                TestContext.AddTestAttachment("C:\\temp\\emailName.JPG");

                //Make a false exception occur
//                Assert.IsTrue(false);

            };
            Assert.IsTrue(ExecuteTest(action, DriverType.Chrome,
strTestName));
        }

So even though I cam run in parallel, I'm specifically running a single
test.

I've attached the generated NUNIT .xml.
Shane

**Comment by msscribner** [comment]
This is the NUNIT report I'm using as input for the GHP Report
[AutomationTestResults_A_00_10232019_151438.txt](https://github.com/GHPReporter/Ghpr.NUnit/files/3772270/AutomationTestResults_A_00_10232019_151438.txt)

**Comment by elv1s42** [comment]
Ok, so am I right that you are using Ghpr.Console to generate the report after test run is finished?
Also can you please check that the screenshot `<filePath>C:\temp\emailName.JPG</filePath>` file exists at the time when the report is generated?

Thank you

**Comment by msscribner** [comment]
My application calls the API  ReportHelper.GenerateReport.
       ReportHelper.GenerateReport(files.ToArray());

The file 'emailName.JPG' physically exists at the location
C:\temp\emailName.JPG.

**Comment by elv1s42** [comment]
Hi @msscribner !
I was able to reproduce the issue, the file `AutomationTestResults_A_00_10232019_151438.txt` helped a lot, thank you. Going to fix it on this weekend and try to release the next week

**Comment by elv1s42** [comment]
Released in v0.9.10
