### ISSUE TITLE
Integrating with .Net Core test project

### ISSUE THREAD

**Issue by zubr7** [GHPReporter/Ghpr.NUnit#77]
**Describe the bug**
First of all I'd like to say thank you for your project!
Unfortunately, I failed to integrate GHPReporter into my project (.Net Core Nunit test project). I didn't receive a generated file.

**To Reproduce**
1. Added the entry below into 'C:\Users\windows_username\.nuget\packages\nunit.consolerunner\3.11.1\tools\nunit.console.nuget.addins':
'addins/../../../Users/windows_username/.nuget/packages/ghpr.nunit/0.9.10/lib/netstandard2.0/Ghpr.NUnit.dll'
2. Copied 'Ghpr.NUnit.Settings.json' file from 'C:\Users\windows_username\.nuget\packages\ghpr.nunit\0.9.10\content' to the root of my project
3. Checked that 'bin\Debug\netcoreapp3.1\' folder contains Ghpr.Core.dll, Ghpr.NUnit.dll, Ghpr.LocalFileSystem.dll, Ghpr.NUnit.Settings.json and Newtonsoft.Json.dll
3. Run my tests by cmd: 'dotnet test -l trx -r report'

**Expected behavior**
A HTML report should be generated. I checked the root of C drive, project root folder, 'bin', 'obj' folders.

**Screenshots**
![image](https://user-images.githubusercontent.com/12113947/76334951-de5edf80-6304-11ea-9662-4c00a180c80d.png)
![image](https://user-images.githubusercontent.com/12113947/76334715-845e1a00-6304-11ea-8b26-695089fa3221.png)

**Versions**
.Net Core 3.1
GHPReporter 0.9.10, 
Nunit 3.12.0, 
Nunit.ColsoleRunner 3.11.1,

**Comment by elv1s42** [comment]
Hi @zubr7 , 
Thank you for the issue and sorry for the late response.
The issue we are having here is that NUnit works a little bit different when running .NET Core tests, see the corresponding issue here: https://github.com/nunit/nunit-console/issues/487

So I had to create a new issue here: https://github.com/GHPReporter/Ghpr.NUnit/issues/57
The idea is that we need a new NuGet package which will be detected automatically by NUnit when running .NET Core tests.

For now, I think it may be possible to use Ghpr.Console package to generate the report from the `.xml` file with test results.

Thank you

**Comment by elv1s42** [comment]
Hi @zubr7,

Now you should be able to use `Ghpr.NUnit` inside your .NET Core test projects.

The solution was to add a new `.addins` file which is detected by `NUnit3TestAdapter`.

So here is a short instruction on how to quickly set up a .NET Core `NUnit` test project with `Ghpr.NUnit` (I'm using VS19):

1. Create a new test project from template:
![image](https://user-images.githubusercontent.com/6689884/76961894-43cb5580-692f-11ea-8cd1-db0d831b42a8.png)

2. Install other required `NuGet` packages, so the full list will be as follows:
``` xml 

    <PackageReference Include="Ghpr.NUnit" Version="0.9.11" />
    <PackageReference Include="nunit" Version="3.12.0" />
    <PackageReference Include="NUnit3TestAdapter" Version="3.15.1" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="16.4.0" />
    <PackageReference Include="Newtonsoft.Json" Version="12.0.3" />
    <PackageReference Include="Ghpr.Core" Version="0.9.10" />
    <PackageReference Include="Ghpr.LocalFileSystem" Version="0.9.10" />
```
3. Make sure to include `Ghpr.NUnit.Settings.json` and `Ghpr.NUnit.addins` files into your project (and mark them with `Copy always` attribute). You can find both files in the corresponding NuGet folder of the `Ghpr.NUnit` package (starting from v0.9.11):
![image](https://user-images.githubusercontent.com/6689884/76962120-aa507380-692f-11ea-8df2-ca122e13af79.png)

4. Run your tests using `dotnet test` command:
![image](https://user-images.githubusercontent.com/6689884/76962193-d2d86d80-692f-11ea-978a-f603f3d3309e.png)

5. See the report generated:
![image](https://user-images.githubusercontent.com/6689884/76962237-eaaff180-692f-11ea-8522-40565babd74b.png)


Please feel free to reopen this issue or raise a new one in case there is something wrong with how the package works for .NET Core tests.

Thank you.
