### ISSUE TITLE
Data not showing in the report

### ISSUE THREAD

**Issue by nagarjunagandra** [GHPReporter/Ghpr.NUnit#8]
Hi,

Files are generated when I ran the Nunit console application but when i open the index file and navigating further not showing any data. it is just showing empty values

Please help me on this.

Regards,
Nagarjuna

**Comment by elv1s42** [comment]
Hi @nagarjunagandra !

What version of Chpr.Core and Ghpr.NUnit are you using?

Are there any errors in browser console when you are opening report?

Are there any exception .txt files the report folder?

Did you follow [these](https://github.com/GHPReporter/Ghpr.Core#view-report-locally) instructions to view report?

**Comment by nagarjunagandra** [comment]
Hi,

I am using 0.2.5.1 version for both Ghpr.core and Ghpr.Nunit.

I could not find any errors in browser console and exceptions in report folder.

**Comment by elv1s42** [comment]
Ok, can you attach this report here? Or maybe create simple demo tests to reproduce this issue.
Is it possible that tests fail inside SetUp?

**Comment by nagarjunagandra** [comment]
Hi ,

 I am able to see the report only in Firefox but not on other browsers.

Please help me to how to enable in other browsers as well.

**Comment by elv1s42** [comment]
The reason why it doesn work is that you need to enable access to local files from javascript, which is blocked by default in all browsers. you will see some errors inside browser console. You can serach for browser options to enable access to local files (like `security.fileuri.strict_origin_policy` parameter for Firefox).

Another way is to create local server (like Apache Tomcat) and put this report on server (you can set output folder to '\\yourserver\reportfolder')
